# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.cache/wt} [current_project]
set_property parent.project_path {C:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {{C:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/hdl/design_PL_Intp_wrapper.v}}
add_files {{C:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/design_PL_Intp.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/ip/design_PL_Intp_processing_system7_0_0/design_PL_Intp_processing_system7_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/ip/design_PL_Intp_axi_timer_0_0/design_PL_Intp_axi_timer_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/ip/design_PL_Intp_axi_timer_0_0/design_PL_Intp_axi_timer_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/ip/design_PL_Intp_rst_ps7_0_100M_0/design_PL_Intp_rst_ps7_0_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/ip/design_PL_Intp_rst_ps7_0_100M_0/design_PL_Intp_rst_ps7_0_100M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/ip/design_PL_Intp_rst_ps7_0_100M_0/design_PL_Intp_rst_ps7_0_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/ip/design_PL_Intp_auto_pc_0/design_PL_Intp_auto_pc_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/design_PL_Intp_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/kab/Downloads/DMA Interrupt/dma_intr/dma_intr.srcs/sources_1/bd/design_PL_Intp/design_PL_Intp.bd}}]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_PL_Intp_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_PL_Intp_wrapper.dcp

catch { report_utilization -file design_PL_Intp_wrapper_utilization_synth.rpt -pb design_PL_Intp_wrapper_utilization_synth.pb }
