# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_PL_Intp/design_PL_Intp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PL_Intp || ORIG_REF_NAME==design_PL_Intp}]

# IP: bd/design_PL_Intp/ip/design_PL_Intp_processing_system7_0_0/design_PL_Intp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PL_Intp_processing_system7_0_0 || ORIG_REF_NAME==design_PL_Intp_processing_system7_0_0}]

# IP: bd/design_PL_Intp/ip/design_PL_Intp_axi_timer_0_0/design_PL_Intp_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PL_Intp_axi_timer_0_0 || ORIG_REF_NAME==design_PL_Intp_axi_timer_0_0}]

# IP: bd/design_PL_Intp/ip/design_PL_Intp_ps7_0_axi_periph_0/design_PL_Intp_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PL_Intp_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_PL_Intp_ps7_0_axi_periph_0}]

# IP: bd/design_PL_Intp/ip/design_PL_Intp_rst_ps7_0_100M_0/design_PL_Intp_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PL_Intp_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_PL_Intp_rst_ps7_0_100M_0}]

# IP: bd/design_PL_Intp/ip/design_PL_Intp_auto_pc_0/design_PL_Intp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PL_Intp_auto_pc_0 || ORIG_REF_NAME==design_PL_Intp_auto_pc_0}]

# XDC: bd/design_PL_Intp/design_PL_Intp_ooc.xdc
