# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_processing_system7_0_0/design_pl_inpp_processing_system7_0_0.xci
# IP: The module: 'design_pl_inpp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_processing_system7_0_0/design_pl_inpp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pl_inpp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_processing_system7_0_0/design_pl_inpp_processing_system7_0_0.xci
# IP: The module: 'design_pl_inpp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_processing_system7_0_0/design_pl_inpp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pl_inpp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
