# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.cache/wt [current_project]
set_property parent.project_path C:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/hdl/design_pl_inpp_wrapper.vhd
add_files C:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/design_pl_inpp.bd
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_processing_system7_0_0/design_pl_inpp_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_axi_timer_0_0/design_pl_inpp_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_axi_timer_0_0/design_pl_inpp_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_rst_ps7_0_100M_0/design_pl_inpp_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_rst_ps7_0_100M_0/design_pl_inpp_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_rst_ps7_0_100M_0/design_pl_inpp_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/ip/design_pl_inpp_auto_pc_0/design_pl_inpp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/design_pl_inpp_ooc.xdc]
set_property is_locked true [get_files C:/Users/kab/Desktop/workspace/PL_INTP/PL_Intp.srcs/sources_1/bd/design_pl_inpp/design_pl_inpp.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_pl_inpp_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_pl_inpp_wrapper.dcp

catch { report_utilization -file design_pl_inpp_wrapper_utilization_synth.rpt -pb design_pl_inpp_wrapper_utilization_synth.pb }
