# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_pl_inpp/design_pl_inpp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_pl_inpp || ORIG_REF_NAME==design_pl_inpp}]

# IP: bd/design_pl_inpp/ip/design_pl_inpp_processing_system7_0_0/design_pl_inpp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_pl_inpp_processing_system7_0_0 || ORIG_REF_NAME==design_pl_inpp_processing_system7_0_0}]

# IP: bd/design_pl_inpp/ip/design_pl_inpp_axi_timer_0_0/design_pl_inpp_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_pl_inpp_axi_timer_0_0 || ORIG_REF_NAME==design_pl_inpp_axi_timer_0_0}]

# IP: bd/design_pl_inpp/ip/design_pl_inpp_ps7_0_axi_periph_0/design_pl_inpp_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_pl_inpp_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_pl_inpp_ps7_0_axi_periph_0}]

# IP: bd/design_pl_inpp/ip/design_pl_inpp_rst_ps7_0_100M_0/design_pl_inpp_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_pl_inpp_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_pl_inpp_rst_ps7_0_100M_0}]

# IP: bd/design_pl_inpp/ip/design_pl_inpp_auto_pc_0/design_pl_inpp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_pl_inpp_auto_pc_0 || ORIG_REF_NAME==design_pl_inpp_auto_pc_0}]

# XDC: bd/design_pl_inpp/design_pl_inpp_ooc.xdc
